name: tubule_segmentation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.5
  - torchvision
  - numpy<2
  - scipy
  - matplotlib
  - tqdm
  - pip
  - pip:
    - opencv-python
    - albumentations
    - huggingface_hub
    - rasterio
    - shapely
    - tifffile
    - scikit-image
    - ijson
